package com.k8s.generator.model;

import java.util.List;
import java.util.Objects;

/**
 * Root specification record - represents the complete input model for generator.
 *
 * <p>This is the internal representation created from CLI arguments or YAML specs.
 * It represents what the user wants to generate, before IP allocation and VM generation.
 *
 * <p>Architecture Position:
 * <pre>
 * CLI Args → SpecConverter → GeneratorSpec → Validator → PlanBuilder → ScaffoldPlan → Renderer
 * </pre>
 *
 * <p>Phase 1 MVP Scope:
 * <ul>
 *   <li><b>Single cluster</b>: clusters list always contains exactly 1 element</li>
 *   <li><b>No management VM</b>: ManagementSpec support deferred to Phase 3</li>
 *   <li><b>Simple engines only</b>: kind and minikube (no kubeadm multi-node)</li>
 * </ul>
 *
 * <p>Validation Strategy (Three-Layer):
 * <ol>
 *   <li><b>Structural</b>: Enforced in this compact constructor
 *       <br>- Non-null fields, non-empty lists, basic invariants</li>
 *   <li><b>Semantic</b>: Enforced by SemanticValidator
 *       <br>- Module format, cluster name patterns, engine-specific rules</li>
 *   <li><b>Policy</b>: Enforced by PolicyValidator
 *       <br>- Cross-cluster constraints, IP overlaps (Phase 3+)</li>
 * </ol>
 *
 * <p>Example Usage:
 * <pre>{@code
 * // Phase 1 MVP: Single kind cluster
 * var spec = new GeneratorSpec(
 *     new ModuleInfo("m1", "pt"),
 *     List.of(
 *         new ClusterSpec(
 *             "clu-m1-pt-kind",
 *             ClusterType.KIND,
 *             Optional.empty(),           // Use default IP
 *             0,                          // KIND: no masters
 *             0,                          // KIND: no workers
 *             SizeProfile.MEDIUM,
 *             List.of()                   // VMs generated by PlanBuilder
 *         )
 *     )
 * );
 *
 * // Future: Multi-cluster kubeadm setup
 * var multiCluster = new GeneratorSpec(
 *     new ModuleInfo("m7", "exam"),
 *     List.of(
 *         new ClusterSpec("staging", ClusterType.KUBEADM, Optional.of("192.168.56.10"), 3, 5, ...),
 *         new ClusterSpec("prod", ClusterType.KUBEADM, Optional.of("192.168.56.30"), 3, 7, ...)
 *     )
 * );
 * }</pre>
 *
 * @param module   Module metadata (module number + type)
 * @param clusters List of cluster specifications (1+ required, Phase 1 = exactly 1)
 * @see ModuleInfo
 * @see ClusterSpec
 * @see ScaffoldPlan
 * @see com.k8s.generator.parser.SpecConverter
 * @since 1.0.0
 */
public record GeneratorSpec(
        ModuleInfo module,
        List<ClusterSpec> clusters) {
    /**
     * Compact constructor with structural validation.
     *
     * <p>Validates:
     * <ul>
     *   <li>All required fields are non-null</li>
     *   <li>Clusters list is non-empty (at least 1 cluster required)</li>
     *   <li>Clusters list contains no null elements</li>
     * </ul>
     *
     * <p>Note: This constructor does NOT validate:
     * <ul>
     *   <li>Module format (handled by ModuleInfo compact constructor)</li>
     *   <li>Cluster specifications (handled by ClusterSpec compact constructor)</li>
     *   <li>Cluster name uniqueness (handled by PolicyValidator)</li>
     *   <li>IP allocation conflicts (handled by PolicyValidator)</li>
     * </ul>
     *
     * @throws IllegalArgumentException if any structural validation fails
     */
    public GeneratorSpec {
        // Null checks
        Objects.requireNonNull(module, "module is required");
        Objects.requireNonNull(clusters, "clusters list is required (use List.of() if empty, but at least 1 required)");

        // Empty check
        if (clusters.isEmpty()) {
            throw new IllegalArgumentException("clusters list cannot be empty (at least 1 cluster required)");
        }

        // Null element check
        if (clusters.stream().anyMatch(Objects::isNull)) {
            throw new IllegalArgumentException("clusters list contains null elements");
        }

        // Make defensive copy to ensure immutability
        clusters = List.copyOf(clusters);
    }

    /**
     * Returns the number of clusters in this specification.
     * For Phase 1 MVP, this is always 1.
     *
     * @return cluster count (1+ for valid specs)
     */
    public int clusterCount() {
        return clusters.size();
    }

    /**
     * Checks if this is a single-cluster specification.
     * Phase 1 MVP only supports single-cluster mode.
     *
     * @return true if clusters.size() == 1
     */
    public boolean isSingleCluster() {
        return clusters.size() == 1;
    }

    /**
     * Checks if this is a multi-cluster specification.
     * Not supported in Phase 1 MVP (returns false always).
     *
     * @return true if clusters.size() > 1
     */
    public boolean isMultiCluster() {
        return clusters.size() > 1;
    }

    /**
     * Returns the primary cluster for single-cluster mode.
     * Throws if called on multi-cluster spec.
     *
     * @return the first (and only) cluster
     * @throws IllegalStateException if not a single-cluster spec
     */
    public ClusterSpec primaryCluster() {
        if (!isSingleCluster()) {
            throw new IllegalStateException(
                    "primaryCluster() called on multi-cluster spec with " + clusters.size() + " clusters"
            );
        }
        return clusters.get(0);
    }

    /**
     * Returns a new GeneratorSpec with updated clusters list.
     * Used by validators or plan builders to update cluster configurations.
     *
     * @param newClusters new clusters list (must not be null or empty)
     * @return new GeneratorSpec with updated clusters
     * @throws IllegalArgumentException if newClusters is null, empty, or contains nulls
     */
    public GeneratorSpec withClusters(List<ClusterSpec> newClusters) {
        Objects.requireNonNull(newClusters, "newClusters cannot be null");
        return new GeneratorSpec(module, newClusters);
    }
}
